-- Database Backup Created: 2025-05-25 19:52:16
-- Generated by Admin Panel


-- Table structure for table `admin_logs`
DROP TABLE IF EXISTS `admin_logs`;
CREATE TABLE `admin_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `action` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_id` int DEFAULT NULL,
  `details` text COLLATE utf8mb4_unicode_ci,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_admin_logs_admin_id` (`admin_id`),
  KEY `idx_admin_logs_action` (`action`),
  KEY `idx_admin_logs_created_at` (`created_at`),
  CONSTRAINT `admin_logs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `admin_logs`
INSERT INTO `admin_logs` VALUES ('1', '2', 'update_user_role', 'user', '1', 'Changed role to: admin', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '2025-05-26 00:51:46');
INSERT INTO `admin_logs` VALUES ('2', '2', 'update_setting', 'setting', NULL, 'Updated maintenance_mode to: 1', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '2025-05-26 00:51:54');
INSERT INTO `admin_logs` VALUES ('3', '2', 'update_setting', 'setting', NULL, 'Updated maintenance_mode to: 0', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36', '2025-05-26 00:52:10');


-- Table structure for table `bank_accounts`
DROP TABLE IF EXISTS `bank_accounts`;
CREATE TABLE `bank_accounts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `bank_username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bank_password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `account_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_sync` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_bank` (`user_id`,`bank_username`),
  KEY `idx_bank_accounts_user_id` (`user_id`),
  CONSTRAINT `bank_accounts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `bank_accounts`
INSERT INTO `bank_accounts` VALUES ('3', '1', 'dinhhung1508', 'RGluaGh1bmcxNTA4MjRA', 'Hung', '2025-05-25 23:47:52', '1', '2025-05-25 22:57:03', NULL);


-- Table structure for table `categories`
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `type` enum('income','expense') COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_categories_user_id` (`user_id`),
  KEY `idx_categories_type` (`type`),
  CONSTRAINT `categories_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `categories`
INSERT INTO `categories` VALUES ('1', '1', 'tiền lương', 'tiền lương tháng', 'income', '2025-03-18 10:45:15', NULL);
INSERT INTO `categories` VALUES ('2', '1', 'mua đồ', 'mua đồ ăn', 'expense', '2025-03-18 11:04:01', NULL);
INSERT INTO `categories` VALUES ('3', '1', 'tiền mua đồ ăn', '', 'expense', '2025-05-24 22:19:20', NULL);
INSERT INTO `categories` VALUES ('4', '1', 'Chi phí khác', '', 'expense', '2025-05-25 23:04:05', NULL);


-- Table structure for table `chat_history`
DROP TABLE IF EXISTS `chat_history`;
CREATE TABLE `chat_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_bot` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_chat_history_user_id` (`user_id`),
  CONSTRAINT `chat_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `chat_history`
INSERT INTO `chat_history` VALUES ('1', '1', 'Quy tắc 50/30/20 là gì?', '0', '2025-03-18 10:05:44');
INSERT INTO `chat_history` VALUES ('2', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:05:44');
INSERT INTO `chat_history` VALUES ('3', '1', 'Làm thế nào để lập ngân sách hiệu quả?', '0', '2025-03-18 10:05:48');
INSERT INTO `chat_history` VALUES ('4', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:05:48');
INSERT INTO `chat_history` VALUES ('5', '1', 'Làm sao để tiết kiệm tiền?', '0', '2025-03-18 10:05:52');
INSERT INTO `chat_history` VALUES ('6', '1', 'Dựa trên dữ liệu hiện tại, bạn đang chi tiêu nhiều hơn hoặc bằng thu nhập hàng tháng. Để có thể tiết kiệm, bạn cần cắt giảm chi tiêu hoặc tăng thu nhập.

Gợi ý: Hãy xem xét các khoản chi tiêu không cần thiết và cố gắng cắt giảm ít nhất 10-15% tổng chi tiêu.', '1', '2025-03-18 10:05:52');
INSERT INTO `chat_history` VALUES ('7', '1', 'Quỹ khẩn cấp là gì?', '0', '2025-03-18 10:06:01');
INSERT INTO `chat_history` VALUES ('8', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:06:01');
INSERT INTO `chat_history` VALUES ('9', '1', 'Làm thế nào để theo dõi chi tiêu hiệu quả?', '0', '2025-03-18 10:06:05');
INSERT INTO `chat_history` VALUES ('10', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:06:05');
INSERT INTO `chat_history` VALUES ('11', '1', 'Làm sao để tiết kiệm tiền?', '0', '2025-03-18 10:49:58');
INSERT INTO `chat_history` VALUES ('12', '1', 'Dựa trên dữ liệu tài chính của bạn, tôi đề xuất kế hoạch tiết kiệm như sau:

- Thu nhập ước tính hàng tháng: 417₫
- Chi tiêu ước tính hàng tháng: 0₫
- Tiềm năng tiết kiệm hàng tháng: 417₫

Kế hoạch tiết kiệm đề xuất:
1. Quỹ khẩn cấp (50%): 208₫/tháng
2. Tiết kiệm dài hạn (30%): 125₫/tháng
3. Quỹ giải trí/cá nhân (20%): 83₫/tháng

Với kế hoạch này, sau 1 năm bạn sẽ tiết kiệm được khoảng 5.000₫.', '1', '2025-03-18 10:49:58');
INSERT INTO `chat_history` VALUES ('13', '1', 'Làm thế nào để lập ngân sách hiệu quả?', '0', '2025-03-18 10:50:04');
INSERT INTO `chat_history` VALUES ('14', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:50:04');
INSERT INTO `chat_history` VALUES ('15', '1', 'Làm thế nào để theo dõi chi tiêu hiệu quả?', '0', '2025-03-18 10:50:11');
INSERT INTO `chat_history` VALUES ('16', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:50:11');
INSERT INTO `chat_history` VALUES ('17', '1', 'Quy tắc 50/30/20 là gì?', '0', '2025-03-18 10:50:13');
INSERT INTO `chat_history` VALUES ('18', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:50:13');
INSERT INTO `chat_history` VALUES ('19', '1', 'Làm sao để giảm chi tiêu hàng tháng?', '0', '2025-03-18 10:50:15');
INSERT INTO `chat_history` VALUES ('20', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:50:15');
INSERT INTO `chat_history` VALUES ('21', '1', 'Quy tắc 50/30/20 là gì?', '0', '2025-03-18 10:50:18');
INSERT INTO `chat_history` VALUES ('22', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-03-18 10:50:18');
INSERT INTO `chat_history` VALUES ('23', '1', 'Hôm nay tôi mua sắm hết 500k', '0', '2025-04-17 23:13:31');
INSERT INTO `chat_history` VALUES ('24', '1', 'Tôi đã ghi nhận khoản chi tiêu của bạn. Bạn có thể lưu giao dịch này bằng cách nhấn nút \'Sửa giao dịch\' bên dưới.', '1', '2025-04-17 23:13:31');
INSERT INTO `chat_history` VALUES ('25', '1', 'Vừa nhận lương 10 triệu', '0', '2025-04-17 23:13:53');
INSERT INTO `chat_history` VALUES ('26', '1', 'Tôi đã ghi nhận khoản thu nhập của bạn. Bạn có thể lưu giao dịch này bằng cách nhấn nút \'Sửa giao dịch\' bên dưới.', '1', '2025-04-17 23:13:53');
INSERT INTO `chat_history` VALUES ('27', '1', 'Hôm qua đi ăn hết 300k, đổ xăng 100k', '0', '2025-04-18 19:58:46');
INSERT INTO `chat_history` VALUES ('28', '1', 'Tôi đã ghi nhận khoản chi tiêu của bạn. Bạn có thể lưu giao dịch này bằng cách nhấn nút \'Sửa giao dịch\' bên dưới.', '1', '2025-04-18 19:58:46');
INSERT INTO `chat_history` VALUES ('29', '1', 'hi', '0', '2025-04-18 20:06:33');
INSERT INTO `chat_history` VALUES ('30', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-04-18 20:06:33');
INSERT INTO `chat_history` VALUES ('31', '1', 'bạn là ai', '0', '2025-04-18 20:06:43');
INSERT INTO `chat_history` VALUES ('32', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-04-18 20:06:43');
INSERT INTO `chat_history` VALUES ('33', '1', 'Hôm qua đi ăn hết 300k, đổ xăng 100k', '0', '2025-04-18 20:10:28');
INSERT INTO `chat_history` VALUES ('34', '1', 'Tôi đã ghi nhận khoản chi tiêu của bạn. Bạn có thể lưu giao dịch này bằng cách nhấn nút \'Sửa giao dịch\' bên dưới.', '1', '2025-04-18 20:10:28');
INSERT INTO `chat_history` VALUES ('35', '1', 'Làm thế nào để lập ngân sách hiệu quả?', '0', '2025-05-10 11:16:37');
INSERT INTO `chat_history` VALUES ('36', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-05-10 11:16:37');
INSERT INTO `chat_history` VALUES ('37', '1', 'Làm thế nào để lập ngân sách hiệu quả?', '0', '2025-05-10 11:16:41');
INSERT INTO `chat_history` VALUES ('38', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-05-10 11:16:41');
INSERT INTO `chat_history` VALUES ('39', '1', 'hi', '0', '2025-05-10 11:16:45');
INSERT INTO `chat_history` VALUES ('40', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-05-10 11:16:45');
INSERT INTO `chat_history` VALUES ('41', '1', 'hi', '0', '2025-05-23 11:47:10');
INSERT INTO `chat_history` VALUES ('42', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-05-23 11:47:10');
INSERT INTO `chat_history` VALUES ('43', '1', 'bạn là ai', '0', '2025-05-23 11:47:15');
INSERT INTO `chat_history` VALUES ('44', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-05-23 11:47:15');
INSERT INTO `chat_history` VALUES ('45', '1', '?', '0', '2025-05-23 11:47:17');
INSERT INTO `chat_history` VALUES ('46', '1', 'Cảm ơn bạn đã liên hệ với tôi. Tôi có thể giúp bạn phân tích tình hình tài chính, đưa ra lời khuyên tiết kiệm, hoặc trả lời các câu hỏi về quản lý tài chính cá nhân. Hãy cho tôi biết bạn cần hỗ trợ gì cụ thể?', '1', '2025-05-23 11:47:17');


-- Table structure for table `notifications`
DROP TABLE IF EXISTS `notifications`;
CREATE TABLE `notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('info','success','warning','error') COLLATE utf8mb4_unicode_ci DEFAULT 'info',
  `is_read` tinyint(1) DEFAULT '0',
  `is_global` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `read_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_user_id` (`user_id`),
  KEY `idx_notifications_is_read` (`is_read`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `notifications`


-- Table structure for table `system_settings`
DROP TABLE IF EXISTS `system_settings`;
CREATE TABLE `system_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `setting_value` text COLLATE utf8mb4_unicode_ci,
  `description` text COLLATE utf8mb4_unicode_ci,
  `setting_type` enum('string','number','boolean','json') COLLATE utf8mb4_unicode_ci DEFAULT 'string',
  `is_public` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `system_settings`
INSERT INTO `system_settings` VALUES ('1', 'site_name', 'Quản Lý Thu Chi', 'Tên website', 'string', '1', '2025-05-26 00:39:13', NULL);
INSERT INTO `system_settings` VALUES ('2', 'maintenance_mode', '0', 'Chế độ bảo trì', 'boolean', '0', '2025-05-26 00:39:13', '2025-05-26 00:52:10');
INSERT INTO `system_settings` VALUES ('3', 'user_registration', '1', 'Cho phép đăng ký mới', 'boolean', '0', '2025-05-26 00:39:13', NULL);
INSERT INTO `system_settings` VALUES ('4', 'max_transactions_per_user', '10000', 'Số giao dịch tối đa mỗi user', 'number', '0', '2025-05-26 00:39:13', NULL);
INSERT INTO `system_settings` VALUES ('5', 'backup_frequency', '24', 'Tần suất backup (giờ)', 'number', '0', '2025-05-26 00:39:13', NULL);
INSERT INTO `system_settings` VALUES ('6', 'session_timeout', '1440', 'Thời gian hết hạn session (phút)', 'number', '0', '2025-05-26 00:39:13', NULL);


-- Table structure for table `transactions`
DROP TABLE IF EXISTS `transactions`;
CREATE TABLE `transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('income','expense') COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date` date NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `bank_transaction_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_bank_import` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_transactions_user_id` (`user_id`),
  KEY `idx_transactions_date` (`date`),
  KEY `idx_transactions_type` (`type`),
  KEY `idx_bank_transaction_id` (`bank_transaction_id`),
  KEY `idx_is_bank_import` (`is_bank_import`),
  CONSTRAINT `transactions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `transactions`
INSERT INTO `transactions` VALUES ('2', '1', '500000.00', 'hi', 'expense', 'mua đồ', '2025-03-18', '2025-03-18 11:04:20', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('3', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 21:09:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('4', '1', '15000000.00', 'lương', 'income', 'tiền lương', '2025-04-18', '2025-04-18 21:09:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('5', '1', '500000.00', 'tiền đi lại', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 21:09:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('6', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 21:54:38', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('7', '1', '15000000.00', 'lương', 'income', 'tiền lương', '2025-04-18', '2025-04-18 21:54:38', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('8', '1', '500000.00', 'tiền đi lại', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 21:54:38', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('9', '1', '900000.00', 'tiền đi lại', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 21:54:38', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('10', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 22:09:49', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('11', '1', '15000000.00', 'lương', 'income', 'tiền lương', '2025-04-18', '2025-04-18 22:09:49', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('12', '1', '500000.00', 'tiền đi lại', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 22:09:49', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('13', '1', '900000.00', 'tiền đi lại', 'expense', 'mua đồ', '2025-04-18', '2025-04-18 22:09:49', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('15', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-04-26', '2025-04-26 16:49:26', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('16', '1', '125000.00', 'Bánh mỳ bỏ lò dăm bông & phomai', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 11:39:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('17', '1', '125000.00', 'Thịt nguội & phomai viên chiên kiểu Tây Ba Nha', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 11:39:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('18', '1', '125000.00', 'Súp kem rau 4 mùa', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 11:39:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('19', '1', '125000.00', 'Xúc xích Đức nướng mù tạt vàng', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 11:39:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('20', '1', '40000.00', 'MILANO', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 11:39:45', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('21', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:21:51', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('22', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:22:37', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('23', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:23:00', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('24', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:23:14', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('25', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:23:14', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('26', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:23:15', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('27', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:23:15', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('28', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-10', '2025-05-10 19:24:08', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('29', '1', '500000.00', 'tiền ăn uống', 'expense', 'mua đồ', '2025-05-23', '2025-05-23 11:52:56', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('30', '1', '56000.00', 'Tiger nâu', 'expense', 'mua đồ', '2025-05-23', '2025-05-23 12:04:58', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('31', '1', '9000.00', 'Bánh tráng', 'expense', 'mua đồ', '2025-05-23', '2025-05-23 12:04:58', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('32', '1', '60000.00', 'Cá lóc chiên mắm xoài', 'expense', 'mua đồ', '2025-05-23', '2025-05-23 12:04:58', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('33', '1', '35000.00', 'Bao tử ếch xào sả', 'expense', 'mua đồ', '2025-05-23', '2025-05-23 12:04:58', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('34', '1', '12000.00', 'Hến xào', 'income', 'tiền lương', '2025-05-23', '2025-05-23 12:04:58', '2025-05-24 01:22:20', NULL, '0');
INSERT INTO `transactions` VALUES ('35', '1', '500000.00', 'tiền quần áo', 'expense', 'mua đồ', '2025-05-24', '2025-05-24 15:55:46', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('36', '1', '56000.00', 'Tiger nâu', 'expense', 'mua đồ', '2025-05-24', '2025-05-24 18:57:47', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('37', '1', '9000.00', 'Bánh tráng', 'expense', 'mua đồ', '2025-05-24', '2025-05-24 18:57:47', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('38', '1', '60000.00', 'Cá Lóc chiên mắm xoài', 'expense', 'mua đồ', '2025-05-24', '2025-05-24 18:57:47', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('39', '1', '35000.00', 'Bao tử ếch xào sa', 'expense', 'mua đồ', '2025-05-24', '2025-05-24 18:57:47', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('40', '1', '12000.00', 'Hến xào', 'expense', 'mua đồ', '2025-05-24', '2025-05-24 18:57:47', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('41', '1', '97000.00', 'CUSTOMER KOVQR 8CHDX6  - Ma giao dich/ Trace  403637 - LE THI HONG TUYET (0947444589)', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('42', '1', '40000.00', 'CUSTOMER KOVQR 8C6R8L  - Ma giao dich/ Trace  701713', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('43', '1', '101000.00', 'CUSTOMER KOVQR 8A6Z6V  - Ma giao dich/ Trace  643528 - LE THI HONG TUYET (0947444589)', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('44', '1', '3512000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ TB783748 - DINH THI KIM CUC (1017139246)', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('45', '1', '68000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 879265 - TA VAN THAN (0937272662)', 'expense', 'Chi phí khác', '2025-05-24', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('46', '1', '40000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ PF401104 - LE THIEN PHAT (1045693900)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('47', '1', '985000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ CZ683518 - HOANG ANH KHOA (8890280617)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('48', '1', '10000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 700648 - MOMO_BAI XE HAI ANH (99MM24159M18099610)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('49', '1', '33000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ I5880590 - BUI VAN PHUOC (107870073150)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('50', '1', '150000.00', 'LE TRAN QUOC BAO LE TRAN QUOC BAO Chuyen tien- Ma GD  ACSP/ Ur621892', 'income', 'Thu nhập khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('51', '1', '134280.00', 'CUSTOMER POSRETAIL-514304734408-5-USD-AUTHC ODE-531614-TID-7N3QWJUF-MID-SXONGQ UGQWWJUTM-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('52', '1', '120000.00', 'CUSTOMER DINH MANH HUNG chuyen tien. DEN: DINH MANH HUNG - DINH MANH HUNG  (0000968948008)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('53', '1', '120000.00', 'CUSTOMER DINH MANH HUNG chuyen tien. TU: DINH MANH HUNG - DINH MANH HUNG  (0000968948008)', 'income', 'Thu nhập khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('54', '1', '3550000.00', 'TRAN HUU DAT MBVCB.9593192710.165540.TRAN HUU DA T chuyen tien.CT tu 0161000879001 T RAN HUU DAT toi 669699669 DINH MANH  HUNG tai MB- Ma GD ACSP/ bl165540', 'income', 'Thu nhập khác', '2025-05-23', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('55', '1', '10000.00', 'BUI VU HUY Qaawgm7172  APPMB1 1  BUI VU HUY CH UYEN TIEN- Ma GD ACSP/ DN863229', 'income', 'Thu nhập khác', '2025-05-22', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('56', '1', '10000.00', 'DINH MANH HUNG QRCODE VNPAY QRCODE DINHHUNG1508250 52215176634960 BP0001mhhl9s . DEN: VNPAY.,JSC#CTY CP GIAI PHAP THANH TOAN VN', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('57', '1', '5000.00', 'DINH MANH HUNG QRCODE VNPAY QRCODE DINHHUNG1508250 52215176520034 BP0001mhhj8m . DEN: VNPAY.,JSC#CTY CP GIAI PHAP THANH TOAN VN', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('58', '1', '600000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ Y8500980 - DANG DINH KINH (0021000527302)', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('59', '1', '1550000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 226544 - NGUYEN HONG SON (19035309130013)', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('60', '1', '40000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 777195 - LUU THE VINH (0987221768)', 'expense', 'Chi phí khác', '2025-05-20', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('61', '1', '53833.00', 'CUSTOMER POSRETAIL-514001558705-53833-VND-A UTHCODE-531613-TID-12345678-MID-00 0980020918994-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-20', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('62', '1', '15000.00', 'CUSTOMER GM1BD64DFMG - Ma giao dich/ Trace 2 68108 - LO VAN THUONG (19073584802012)', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('63', '1', '31000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ 74508037 - NGUYEN QUANG TIEN (0541000305763)', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('64', '1', '55146.00', 'CUSTOMER RetailVisa-762707-55146-VND-513919 493688', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('65', '1', '214666.00', 'CUSTOMER POSRETAIL-513902827066-8-USD-AUTHC ODE-531612-TID-7N3QWJUF-MID-SXONGQ UGQWWJUTM-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('66', '1', '7535.00', 'CUSTOMER POSRETAIL-513815555412-450-NGN-AUT HCODE-531611-TID-99999999-MID-4204 29000211321-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-18', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('67', '1', '20.00', 'Tra lai tien gui, so TK: 0000968948008-20250517', 'income', 'Thu nhập khác', '2025-05-18', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('68', '1', '167.00', 'Tra lai tien gui, so TK: 646263-20250517', 'income', 'Thu nhập khác', '2025-05-18', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('69', '1', '544.00', 'Tra lai tien gui, so TK: 669699669-20250517', 'income', 'Thu nhập khác', '2025-05-18', '2025-05-25 22:42:06', NULL, NULL, '0');
INSERT INTO `transactions` VALUES ('70', '1', '97000.00', 'CUSTOMER KOVQR 8CHDX6  - Ma giao dich/ Trace  403637 - LE THI HONG TUYET (0947444589)', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 23:06:16', NULL, '25/05/2025 19:08:47_97000_CUSTOMER KOVQR 8CHDX', '1');
INSERT INTO `transactions` VALUES ('71', '1', '40000.00', 'CUSTOMER KOVQR 8C6R8L  - Ma giao dich/ Trace  701713', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 23:06:16', NULL, '25/05/2025 18:22:16_40000_CUSTOMER KOVQR 8C6R8', '1');
INSERT INTO `transactions` VALUES ('72', '1', '101000.00', 'CUSTOMER KOVQR 8A6Z6V  - Ma giao dich/ Trace  643528 - LE THI HONG TUYET (0947444589)', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 23:06:16', NULL, '25/05/2025 12:59:41_101000_CUSTOMER KOVQR 8A6Z6', '1');
INSERT INTO `transactions` VALUES ('73', '1', '3512000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ TB783748 - DINH THI KIM CUC (1017139246)', 'expense', 'Chi phí khác', '2025-05-25', '2025-05-25 23:06:16', NULL, '25/05/2025 01:36:21_3512000_DINH MANH HUNG DINH ', '1');
INSERT INTO `transactions` VALUES ('74', '1', '68000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 879265 - TA VAN THAN (0937272662)', 'expense', 'Chi phí khác', '2025-05-24', '2025-05-25 23:06:16', NULL, '24/05/2025 12:46:59_68000_CUSTOMER DINH MANH H', '1');
INSERT INTO `transactions` VALUES ('75', '1', '40000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ PF401104 - LE THIEN PHAT (1045693900)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 23:55:28_40000_DINH MANH HUNG DINH ', '1');
INSERT INTO `transactions` VALUES ('76', '1', '985000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ CZ683518 - HOANG ANH KHOA (8890280617)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 22:20:57_985000_DINH MANH HUNG DINH ', '1');
INSERT INTO `transactions` VALUES ('77', '1', '10000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 700648 - MOMO_BAI XE HAI ANH (99MM24159M18099610)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 13:56:14_10000_CUSTOMER DINH MANH H', '1');
INSERT INTO `transactions` VALUES ('78', '1', '33000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ I5880590 - BUI VAN PHUOC (107870073150)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 12:51:33_33000_DINH MANH HUNG DINH ', '1');
INSERT INTO `transactions` VALUES ('79', '1', '150000.00', 'LE TRAN QUOC BAO LE TRAN QUOC BAO Chuyen tien- Ma GD  ACSP/ Ur621892', 'income', 'Thu nhập khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 11:48:44_150000_LE TRAN QUOC BAO LE ', '1');
INSERT INTO `transactions` VALUES ('80', '1', '134280.00', 'CUSTOMER POSRETAIL-514304734408-5-USD-AUTHC ODE-531614-TID-7N3QWJUF-MID-SXONGQ UGQWWJUTM-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 11:47:04_134280_CUSTOMER POSRETAIL-5', '1');
INSERT INTO `transactions` VALUES ('81', '1', '120000.00', 'CUSTOMER DINH MANH HUNG chuyen tien. DEN: DINH MANH HUNG - DINH MANH HUNG  (0000968948008)', 'expense', 'Chi phí khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 11:46:45_120000_CUSTOMER DINH MANH H', '1');
INSERT INTO `transactions` VALUES ('82', '1', '3550000.00', 'TRAN HUU DAT MBVCB.9593192710.165540.TRAN HUU DA T chuyen tien.CT tu 0161000879001 T RAN HUU DAT toi 669699669 DINH MANH  HUNG tai MB- Ma GD ACSP/ bl165540', 'income', 'Thu nhập khác', '2025-05-23', '2025-05-25 23:06:16', NULL, '23/05/2025 00:35:47_3550000_TRAN HUU DAT MBVCB.9', '1');
INSERT INTO `transactions` VALUES ('83', '1', '10000.00', 'BUI VU HUY Qaawgm7172  APPMB1 1  BUI VU HUY CH UYEN TIEN- Ma GD ACSP/ DN863229', 'income', 'Thu nhập khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 15:49:49_10000_BUI VU HUY Qaawgm717', '1');
INSERT INTO `transactions` VALUES ('84', '1', '10000.00', 'DINH MANH HUNG QRCODE VNPAY QRCODE DINHHUNG1508250 52215176634960 BP0001mhhl9s . DEN: VNPAY.,JSC#CTY CP GIAI PHAP THANH TOAN VN', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 15:17:40_10000_DINH MANH HUNG QRCOD', '1');
INSERT INTO `transactions` VALUES ('85', '1', '5000.00', 'DINH MANH HUNG QRCODE VNPAY QRCODE DINHHUNG1508250 52215176520034 BP0001mhhj8m . DEN: VNPAY.,JSC#CTY CP GIAI PHAP THANH TOAN VN', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 15:17:01_5000_DINH MANH HUNG QRCOD', '1');
INSERT INTO `transactions` VALUES ('86', '1', '10000.00', 'DINH MANH HUNG QRCODE VNPAY QRCODE DINHHUNG1508250 52215166457711 BP0001mhhk34 . DEN: VNPAY.,JSC#CTY CP GIAI PHAP THANH TOAN VN', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 15:16:39_10000_DINH MANH HUNG QRCOD', '1');
INSERT INTO `transactions` VALUES ('87', '1', '10000.00', 'DINH MANH HUNG QRCODE VNPAY QRCODE DINHHUNG1508250 52215146026501 BP0001mhhf2e . DEN: VNPAY.,JSC#CTY CP GIAI PHAP THANH TOAN VN', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 15:14:06_10000_DINH MANH HUNG QRCOD', '1');
INSERT INTO `transactions` VALUES ('88', '1', '600000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ Y8500980 - DANG DINH KINH (0021000527302)', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 09:56:31_600000_DINH MANH HUNG DINH ', '1');
INSERT INTO `transactions` VALUES ('89', '1', '1550000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 226544 - NGUYEN HONG SON (19035309130013)', 'expense', 'Chi phí khác', '2025-05-22', '2025-05-25 23:06:16', NULL, '22/05/2025 09:47:40_1550000_CUSTOMER DINH MANH H', '1');
INSERT INTO `transactions` VALUES ('90', '1', '40000.00', 'CUSTOMER DINH MANH HUNG chuyen tien - Ma gia o dich/ Trace 777195 - LUU THE VINH (0987221768)', 'expense', 'Chi phí khác', '2025-05-20', '2025-05-25 23:06:16', NULL, '20/05/2025 12:05:27_40000_CUSTOMER DINH MANH H', '1');
INSERT INTO `transactions` VALUES ('91', '1', '53833.00', 'CUSTOMER POSRETAIL-514001558705-53833-VND-A UTHCODE-531613-TID-12345678-MID-00 0980020918994-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-20', '2025-05-25 23:06:16', NULL, '20/05/2025 08:05:17_53833_CUSTOMER POSRETAIL-5', '1');
INSERT INTO `transactions` VALUES ('92', '1', '15000.00', 'CUSTOMER GM1BD64DFMG - Ma giao dich/ Trace 2 68108 - LO VAN THUONG (19073584802012)', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 23:06:16', NULL, '19/05/2025 20:16:49_15000_CUSTOMER GM1BD64DFMG', '1');
INSERT INTO `transactions` VALUES ('93', '1', '31000.00', 'DINH MANH HUNG DINH MANH HUNG chuyen tien- Ma GD A CSP/ 74508037 - NGUYEN QUANG TIEN (0541000305763)', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 23:06:16', NULL, '19/05/2025 19:04:39_31000_DINH MANH HUNG DINH ', '1');
INSERT INTO `transactions` VALUES ('94', '1', '55146.00', 'CUSTOMER RetailVisa-762707-55146-VND-513919 493688', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 23:06:16', NULL, '19/05/2025 14:00:52_55146_CUSTOMER RetailVisa-', '1');
INSERT INTO `transactions` VALUES ('95', '1', '214666.00', 'CUSTOMER POSRETAIL-513902827066-8-USD-AUTHC ODE-531612-TID-7N3QWJUF-MID-SXONGQ UGQWWJUTM-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-19', '2025-05-25 23:06:16', NULL, '19/05/2025 09:48:11_214666_CUSTOMER POSRETAIL-5', '1');
INSERT INTO `transactions` VALUES ('96', '1', '7535.00', 'CUSTOMER POSRETAIL-513815555412-450-NGN-AUT HCODE-531611-TID-99999999-MID-4204 29000211321-TRXCODE-', 'expense', 'Chi phí khác', '2025-05-18', '2025-05-25 23:06:16', NULL, '18/05/2025 22:57:12_7535_CUSTOMER POSRETAIL-5', '1');
INSERT INTO `transactions` VALUES ('97', '1', '20.00', 'Tra lai tien gui, so TK: 0000968948008-20250517', 'income', 'Thu nhập khác', '2025-05-18', '2025-05-25 23:06:16', NULL, '18/05/2025 02:33:49_20_Tra lai tien gui, so', '1');
INSERT INTO `transactions` VALUES ('98', '1', '167.00', 'Tra lai tien gui, so TK: 646263-20250517', 'income', 'Thu nhập khác', '2025-05-18', '2025-05-25 23:06:16', NULL, '18/05/2025 01:38:45_167_Tra lai tien gui, so', '1');
INSERT INTO `transactions` VALUES ('99', '1', '544.00', 'Tra lai tien gui, so TK: 669699669-20250517', 'income', 'Thu nhập khác', '2025-05-18', '2025-05-25 23:06:16', NULL, '18/05/2025 00:01:08_544_Tra lai tien gui, so', '1');


-- Table structure for table `users`
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` enum('user','admin') COLLATE utf8mb4_unicode_ci DEFAULT 'user',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `users`
INSERT INTO `users` VALUES ('1', 'Hoàng Thoại Vỹ', 'dinhhung1508', 'admin2@hacker2k4.com', '$2y$10$l5AvfSTPD5anUR1uN05tiudTK3wYe6EOs8sT/2yMYKZ0UTnQlG9Gi', 'admin', '2025-03-18 09:47:32', NULL, '2025-05-26 00:52:01');
INSERT INTO `users` VALUES ('2', 'Admin', 'admin', 'admin@example.com', '$2y$10$l5AvfSTPD5anUR1uN05tiudTK3wYe6EOs8sT/2yMYKZ0UTnQlG9Gi', 'admin', '2025-05-26 00:39:13', NULL, '2025-05-26 00:51:15');

